import Head from "next/head";
import { Accordion, Grid, GridItem } from "@chakra-ui/react";
import { getPokemons } from "@/lib/pokemon";
import { PokemonAccordion } from "@/components/PokemonAccordion";

interface HomeProps {
  pokemons: {
    name: string;
    url: string;
  }[];
  onAddPokemon: () => void;
}

export default function Home({ pokemons, onAddPokemon }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Accordion allowToggle>
        <Grid templateColumns="repeat(3, 1fr)" gap={6}>
          {pokemons.map((pokemon, index) => (
            <GridItem key={pokemon.name}>
              <PokemonAccordion pokemonName={pokemon.name} index={index + 1} />
            </GridItem>
          ))}
        </Grid>
      </Accordion>
    </>
  );
}

export const getServerSideProps = async () => {
  const pokemons = await getPokemons();

  return {
    props: {
      pokemons: pokemons.results,
    },
  };
};
