import Head from "next/head";
import { getPokemons } from "@/lib/pokemon";
import { PokemonList } from "@/components/PokemonList";
import { PokemonFromList } from "@/types/types";

interface HomeProps {
  pokemons: PokemonFromList[];
}

export default function Home({ pokemons }: HomeProps) {
  return (
    <>
      <Head>
        <title>Pokemon Team Maker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PokemonList pokemons={pokemons} />
    </>
  );
}

export const getServerSideProps = async () => {
  const pokemons = await getPokemons();

  return {
    props: {
      pokemons: pokemons.results,
    },
  };
};
